import type { Metadata } from "next";
import { Playfair_Display, Poppins } from 'next/font/google'
import "./globals.css";
import 'swiper/css';
import 'swiper/css/navigation';
import CartSidebar from "@/components/CartSidebar";
import QuickViewModal from "@/components/QuickViewModal";


const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-playfair',
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${poppins.variable} antialiased`}
      >
        {children}
        <CartSidebar />
        <QuickViewModal />
      </body>
    </html>
  );
}
