import type { Metadata } from "next";
import { Playfair_Display, Poppins } from 'next/font/google'
import "./globals.css";
import 'swiper/css';
import 'swiper/css/navigation';
import CartSidebar from "@/components/CartSidebar";
import QuickViewModal from "@/components/QuickViewModal";
import Navbar from "@/app/Navbar/page";
import Footer from "@/app/Footer/page";

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-playfair',
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: "LuxaHamp - E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${poppins.variable} antialiased flex flex-col min-h-screen`}
      >
        <Navbar />
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
        <CartSidebar />
        <QuickViewModal />
      </body>
    </html>
  );
}
